### ISSUE TITLE
状态栏图标消失,但代理是生效的

### ISSUE THREAD

**Issue by ganhang** [felix-xuu/ShadowsocksX-NG-RX#1]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.14.4 (18E226)
- Shadowsocksx-NG-RX  2.0.5

**Expected behavior:**
点击app，状态栏出现小飞机图标

**Actual behavior:**
点击app，状态栏未出现小飞机图标，多次点击提示软件已启动。。强制退出里未发现进程。
但ssr-privoxy.log文件一直重复打印
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/ghpc/Library/Application Support/ShadowsocksX-NG-RX/privoxy
  Reason: image not found
卸载重装还是不行，使用其他版本ss可正常运行。
(N/A for feature requests)

**Steps to reproduce:**
刚开始是好的，不知道点了啥闪退了，然后就启动不了了。
(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ssr-local.log**

_2019-10-10 17:14:56 INFO: using tcp fast open
 2019-10-10 17:14:56 INFO: initializing ciphers... aes-256-gcm
 2019-10-10 17:14:56 INFO: listening at 127.0.0.1:1086
 2019-10-10 17:14:56 INFO: tcp port reuse enabled_

**Crash Log**
`Process:               privoxy [9048]
Path:                  /Users/USER/Library/Application Support/ShadowsocksX-NG-RX/*/privoxy
Identifier:            privoxy
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           privoxy [9048]
User ID:               501

Date/Time:             2019-10-10 17:22:07.543 +0800
OS Version:            Mac OS X 10.14.4 (18E226)
Report Version:        12
Anonymous UUID:        E53B8FC9-87DD-8FC9-09E6-7046D82A682F

Time Awake Since Boot: 13000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/USER/Library/Application Support/ShadowsocksX-NG-RX/privoxy
  Reason: image not found

Binary Images:
       0x106d13000 -        0x106d4dff3 +privoxy (0) <BCA4A73D-E27E-34A8-B9A3-ADC80D4A839F> /Users/USER/Library/Application Support/ShadowsocksX-NG-RX/privoxy
       0x1149e7000 -        0x114a516ef  dyld (655.1.1) <F217F7F8-A795-3109-B77F-B1E2277F3E3B> /usr/lib/dyld
    0x7fff5bb22000 -     0x7fff5bb34ff7  libz.1.dylib (70.200.4) <FDF169F3-F992-3E8E-B3F7-D4134FEBAE41> /usr/lib/libz.1.dylib`

**Comment by felix-xuu** [comment]
你好，应该是编译时生成了新的证书导致旧证书失效了，所以无法打开app，可以试下最新版本。

**Comment by ganhang** [comment]
你好，可能上面描述写错了，我是用的2.0.5最新版的。。

**Comment by ganhang** [comment]
另外，我发给我同事，他是可以打开。。我之前也可以打开，后面闪退了一次就不行了。。可能是我换了多个版本（其他开源项目）的

**Comment by felix-xuu** [comment]
你好，可以在本地执行brew install pcre安装相关包或者安装2.0.6

**Comment by ganhang** [comment]
好的，我试试
