### ISSUE TITLE
Cannot open on Mac Big Sur

### ISSUE THREAD

**Issue by wuxiaoqiang12** [felix-xuu/ShadowsocksX-NG-RX#11]
The system said:“ShadowsocksX-NG-RX” will damage your computer. You should move it to the Trash.

![image](https://user-images.githubusercontent.com/39110174/99140879-770de200-2680-11eb-8488-c8daef7b0956.png)

**Comment by felix-xuu** [comment]
Please try these steps:
1. Redownload version 2.2.0 at https://github.com/felix-xuu/ShadowsocksX-NG-RX/releases/tag/v2.2.0 ;
2. Unpack the file;
3. Open it (DO NOT forget check security and privacy).
![image](https://user-images.githubusercontent.com/17977441/99141440-49c43280-2686-11eb-8dbf-e5e06493a877.png)
    If still not work, i will check the signature again.

**Comment by wuxiaoqiang12** [comment]
Great, It works now. Thanks
