### ISSUE TITLE
希望能在高级设置里添加上修改socks5 和 http 监听地址的选项。

### ISSUE THREAD

**Issue by jappiter1** [felix-xuu/ShadowsocksX-NG-RX#2]
希望可以自己选择是监听本机127.0.0.1，或者全局监听0.0.0.0

**Comment by jappiter1** [comment]
分组名称无法直接修改，似乎是个bug，新建分组后添加节点，并在节点里设置分组名字，依旧是修改不成功。

**Comment by jappiter1** [comment]
还有一个问题：节点的列表，节点的顺序无法手动更改，似乎也不是按备注名自动排列。

**Comment by felix-xuu** [comment]
你好，
1. 监听地址修改功能会考虑加回来；
2.目前确实没有提供分组名称修改的功能，下个版本一起加上吧，服务器配置右侧中的分组名称其实只是 
   为了显示订阅方提供的名称；
3.目前确实没有排序功能，暂未考虑增加。
