### ISSUE TITLE
verbose mode 无效果

### ISSUE THREAD

**Issue by dfang** [felix-xuu/ShadowsocksX-NG-RX#4]
verbose mode 不能看到什么域名走代理 什么域名直连 

类似 https://github.com/shadowsocks/ShadowsocksX-NG/issues/1195

我也试了下这个版本，勾上verbose mode
然后ps aux | grep ss-local

```
/Users/mj/Library/Application Support/ShadowsocksX-NG-RX/ss-local -c ss-local-config.json --reuse-port --fast-open
```
没有看到 -v 参数

**Comment by felix-xuu** [comment]
你好，确实没有立即生效，下个版本一起修复，当前版本可以重启app生效.

**Comment by df1228** [comment]
重启了也没有生效

**Comment by felix-xuu** [comment]
你好，直接使用2.1.0版本吧.
