### ISSUE TITLE
如何支持cipher为none的加密方法

### ISSUE THREAD

**Issue by df1228** [felix-xuu/ShadowsocksX-NG-RX#5]
用了一些 IPLC的线路，cipher为none， 

```
 2019-11-14 15:22:07 INFO: initializing ciphers... none
 2019-11-14 15:22:07 ERROR: invalid cipher name: none
 2019-11-14 15:22:07 ERROR: failed to initialize ciphers
```

可以支持加密方法为none吗？ 或者指点我一下 告诉修改哪一块的代码，我自己来编译一个版本

**Comment by felix-xuu** [comment]
你好，该项目所依赖的项目shadowsocks-libev不支持加密方式为none.

**Comment by df1228** [comment]
嗯，验证了下，确实如此，

shadowsocksx-ng-r8 打包的 ss-local 是 2.5.6， 从 ~/Library/Application Support/ShadowsocksX-NG/ss-local-2.5.6.12.static可以看到，而[2.5.6](https://github.com/shadowsocks/shadowsocks-libev/blob/v2.5.6/src/encrypt.h#L124)支持none， 最新的[shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev/tree/master/src)已经找不到none了，貌似移除了。。。 看来只有联系服务商升级了

谢谢！
