### ISSUE TITLE
haproxy CPU占用率超高

### ISSUE THREAD

**Issue by dfang** [felix-xuu/ShadowsocksX-NG-RX#6]
退出了shadowsockx-ng-rx, 但是haproxy没有退出，haproxy CPU占用率98%  ....

上传截图老是失败，但我确定haproxy是shadowsockx-ng-rx打开的，活动监视器里可以看到

**Comment by felix-xuu** [comment]
你好，正常退出或者手动关闭负载均衡都是能退出的。你配置的节点个数是否过多呢？默认配置的最大连接数为256。也可以执行tail -f ~/Library/Logs/ssr-haproxy.log看看是否haproxy有异常。如果都看不出问题，手动先杀掉进程吧，可能是haproxy当前版本的一个bug，下个版本会升级haproxy.

**Comment by dfang** [comment]
应该没超过256个
