### ISSUE TITLE
负载均衡 无节点可选   通过二维码扫描进来的地址会创建多个相同名称分组

### ISSUE THREAD

**Issue by linai081795** [felix-xuu/ShadowsocksX-NG-RX#7]
**
![image](https://user-images.githubusercontent.com/12321385/71302001-2a267a80-23e1-11ea-8ae2-0898d2777ea6.png)
**

**Comment by linai081795** [comment]
gao'ji高级设置 保存无效

**Comment by felix-xuu** [comment]
你好，每次扫描会创建新的分组是设计如此，负载均衡只针对订阅节点，高级设置哪个选项没有保存呢？

**Comment by bosconb** [comment]
为啥会设计成扫描一下都会创建全新分组，感觉没法自动分组特别不适应

**Comment by felix-xuu** [comment]
主要是为了避免非订阅形式导入的节点都存在于一个分组中，后面会考虑选择导入节点时让用户选择需要归类进哪个非订阅分组。
